export const ActionType = {
    HOVER_ON: 'HOVER_ON',
    HOVER_OFF: 'HOVER_OFF',
    PLAY: 'PLAY',
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',
    LIST_FAVORITES: 'LIST_FAVORITES',
    LIST_FAVORITES_FAILURE: 'LIST_FAVORITES_FAILURE',
    ADDED_FAVORITE: 'ADDED_FAVORITE',
    ADDED_FAVORITE_FAILURE: 'ADDED_FAVORITE_FAILURE',
    CHECK_FAVORITE: 'CHECK_FAVORITE',
    UNFAVORITE_TRACK : 'UNFAVORITE_TRACK',
    UNFAVORITE_TRACK_FAILURE : 'UNFAVORITE_TRACK_FAILURE',
    ARTIST_SEARCH_SUCCESS : 'ARTIST_SEARCH_SUCCESS',
    ARTIST_SEARCH_FAILURE : 'ARTIST_SEARCH_FAILURE',
    ALBUM_SEARCH_SUCCESS : 'ALBUM_SEARCH_SUCCESS',
    ALBUM_SEARCH_FAILURE : 'ALBUM_SEARCH_FAILURE'
};

export const AuthActionType = {
    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOFF: 'LOGOFF',
    USER_AUTH_START: 'USER_AUTH_START',
    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE'
};

export const ModalActionType = {
    OPEN_ARTIST: 'OPEN_ARTIST',
    CLOSE_ARTIST : 'CLOSE_ARTIST',
    OPEN_ALBUM: 'OPEN_ALBUM',
    CLOSE_ALBUM : 'CLOSE_ALBUM',
    HOVER_ARTIST_ON: 'HOVER_ARTIST_ON',
    HOVER_ARTIST_OFF: 'HOVER_ARTIST_OFF'
};