export const ActionType = {
    HOVER: 'HOVER',
    PLAY: 'PLAY',
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',
    LIST_FAVORITES: 'LIST_FAVORITES',
    LIST_FAVORITES_FAILURE: 'LIST_FAVORITES_FAILURE',
    ADDED_FAVORITE: 'ADDED_FAVORITE',
    ADDED_FAVORITE_FAILURE: 'ADDED_FAVORITE_FAILURE'
};

export const AuthActionType = {
    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOFF: 'LOGOFF',
    USER_AUTH_START: 'USER_AUTH_START',
    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE'
};